DROP TABLE IF EXISTS RESTAURANTS;
DROP TABLE IF EXISTS GRADES;

CREATE TABLE RESTAURANTS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    RESTAURANT_ID VARCHAR(64) NOT NULL,
    BOROUGH VARCHAR(64) NOT NULL,
    BUILDING VARCHAR(64) NOT NULL,
    CUISINE_TYPE VARCHAR(64) NOT NULL,
    LATITUDE VARCHAR(64) NOT NULL,
    LONGITUDE VARCHAR(64) NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    STREET VARCHAR(64) NOT NULL,
    ZIP VARCHAR(10) NOT NULL
);

CREATE TABLE GRADE(
    GRADE_ID INT PRIMARY KEY AUTO_INCREMENT,
    GRADE_TIMESTAMP INT NOT NULL,
    SCORE INT NOT NULL,
    GRADE VARCHAR(5) NOT NULL,
    RESTAURANT_ID INT NOT NULL
);